export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAILED = 'ADMIN_LOGIN_FAILED';
export const ADMIN_LOG_OUT = 'ADMIN_LOG_OUT';
export const ADD_BUS_SUCCESS = 'ADD_BUS_SUCCESS';
export const ADD_BUS_FAILED = 'ADD_BUS_FAILED';
export const FETCH_BUSES_SUCCESS = 'FETCH_BUSES_SUCCESS';
export const FETCH_BUSES_FAILED = 'FETCH_BUSES_FAILED';
export const CLEAR_BUSES_FAILED = 'CLEAR_BUSES_FAILED';
